version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    command: >
      /bin/bash -c "
        cd /var/www/html &&
        composer install &&
        apache2-foreground
      "
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persistência de dados
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mapeando o init.sql para inicializar o banco de dados

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    depends_on:
      - db

volumes:
  db_data:
